server:
  port: 9097
  
spring:
  data:
    mongodb:
#      uri: mongodb+srv://root:password007@cluster0-cjhrd.gcp.mongodb.net/scorpious-demo?retryWrites=true&w=majority
      host: localhost
      port: 27017
      
      database: scorpious-demo


        
redis:
    host: localhost
    port: 6379    
          
logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.asiczen: TRACE
  file:
    name: ./analytics-service.log
    max-size: 10 MB      
    
    
app.idle.time: 900000


